# -*- coding: utf-8 -*-
"""Untitled23.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JEB02PAL2YHjXAUeRfSiLgbvhCAriaSO
"""

import smtplib
from email.mime.text import MIMEText

def send_email():
    sender = "hello@demomailtrap.co"
    receiver = "rajunitnaware8@gmail.com"
    username = "api"
    password = "b001a89b4c0499949500529f76197686"

    msg = MIMEText("Hello Sunny, this is a test email via Mailtrap.")
    msg["Subject"] = "SMTP Test"
    msg["From"] = sender
    msg["To"] = receiver

    try:
        s = smtplib.SMTP("live.smtp.mailtrap.io", 587)
        s.starttls()
        s.login(username, password)
        s.sendmail(sender, receiver, msg.as_string())
        s.quit()
        print("Email sent successfully.")
    except Exception as e:
        print("Error:", e)

send_email()